# Digital Ocean App Platform Configuration
# This file defines how your app is deployed on Digital Ocean

name: alcel-marine-app

# Region where the app will be deployed
region: nyc

# Services definition
services:
  # Backend API Service
  - name: api
    # Use Node.js environment
    environment_slug: node-js

    # GitHub integration
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/alcel-marine-app

    # Build configuration
    build_command: npm install --production=false

    # Run command for production
    run_command: npm run start:production

    # Environment variables
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: "production"

      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "8080"

      # Secret variables (set these in Digital Ocean dashboard)
      - key: MONGODB_URI
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: JWT_REFRESH_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET

      - key: SESSION_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET

    # Health check configuration
    health_check:
      http_path: /api/health
      initial_delay_seconds: 20
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # HTTP port configuration
    http_port: 8080

    # Instance size and count
    instance_count: 1
    instance_size_slug: basic-xxs

    # Routes
    routes:
      - path: /api

  # Static Frontend Service
  - name: web
    environment_slug: node-js

    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/alcel-marine-app

    build_command: npm install && npm run build

    # Serve static files
    run_command: npm run preview

    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: "production"

    http_port: 8080

    instance_count: 1
    instance_size_slug: basic-xxs

    routes:
      - path: /

# Static sites (alternative for frontend)
# Uncomment if you prefer to use static site hosting
# static_sites:
#   - name: web
#     github:
#       branch: main
#       deploy_on_push: true
#       repo: YOUR_GITHUB_USERNAME/alcel-marine-app
#     build_command: npm install && npm run build
#     output_dir: dist
#     routes:
#       - path: /

# Database (if using Digital Ocean Managed MongoDB)
# databases:
#   - name: alcel-marine-db
#     engine: MONGODB
#     production: true
#     version: "6"
